# Built upon minimal .travis.yml from https://github.com/xd009642/tarpaulin

language: rust
# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev

os:
  - linux

cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  - CARGO_PARAMS=""
  - CARGO_PARAMS="--features derive"
  - CARGO_PARAMS="--features num"
  - CARGO_PARAMS="--all-features"
  - CARGO_PARAMS="--no-default-features"
  - CARGO_PARAMS="--no-default-features --features derive" 
  - CARGO_PARAMS="--no-default-features --features num"
  - CARGO_PARAMS="--no-default-features --features derive,num"

jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

before_script: |
  if [ "$TRAVIS_RUST_VERSION" == stable ] && [ CARGO_PARAMS == "--all-features" ]; then
    cargo install cargo-tarpaulin
  fi

script:
- cd float_eq
- cargo clean
- cargo build $CARGO_PARAMS
- cargo test $CARGO_PARAMS

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == stable ] && [ "$CARGO_PARAMS" == "--all-features" ]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin $CARGO_PARAMS --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --exclude-files tests/derive_tests/* --exclude-files ../float_eq_derive/*

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin $CARGO_PARAMS --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi